name = "polarizedionsnet"
type = "webpack"
account_id = "bdd2b66da2d11403b76534a553e1d8dc"
workers_dev = false
route = "polarizedions.net/*"
zone_id = "b293c82295ca531cb2104565c40686d2"

[site]
bucket = "./dist"
entry-point = "workers-site"
